name: Fetch API Data

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  fetch-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          ref: main
          path: main
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install
        working-directory: ./main

      - name: Fetch API data
        env:
          GITHUB_TOKEN: ${{ secrets.API_KEY }}
        run: node scripts/fetchData.js
        working-directory: ./main

      - name: Checkout gh-pages branch
        uses: actions/checkout@v3
        with:
          ref: gh-pages
          path: gh-pages
          fetch-depth: 0

      - name: Copy generated data to gh-pages
        run: |
          cp main/public/base_data.json gh-pages/data/
          cp main/public/news_data.json gh-pages/data/

      - name: Commit & push changes
        working-directory: ./gh-pages
        run: |
          git config user.name "${{ secrets.TECHNICAL_USER_NAME }}"
          git config user.email "${{ secrets.TECHNICAL_USER_MAIL }}"
          git add data/base_data.json data/news_data.json
          git diff --quiet && git diff --staged --quiet || git commit -m "Update API data"
          git push origin gh-pages
